/**
 * Armor Sub-Effects (Defense)
 *
 * 17 sub-effects for the Armor module, focused on survival and protection.
 * Data sourced from docs/subeffects.md.
 */

import type { SubEffectConfig } from '../types';

export const ARMOR_SUB_EFFECTS: SubEffectConfig[] = [
  {
    id: 'healthRegen',
    displayName: 'Health Regen',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: 20,
      rare: 40,
      epic: 60,
      legendary: 100,
      mythic: 200,
      ancestral: 400,
    },
  },
  {
    id: 'defensePercent',
    displayName: 'Defense %',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: 1,
      rare: 2,
      epic: 3,
      legendary: 5,
      mythic: 6,
      ancestral: 8,
    },
  },
  {
    id: 'defenseAbsolute',
    displayName: 'Defense Absolute',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: 15,
      rare: 25,
      epic: 40,
      legendary: 100,
      mythic: 500,
      ancestral: 1000,
    },
  },
  {
    id: 'thornsDamage',
    displayName: 'Thorns Damage',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: 2,
      legendary: 4,
      mythic: 7,
      ancestral: 10,
    },
  },
  {
    id: 'lifesteal',
    displayName: 'Lifesteal',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: 0.3,
      legendary: 0.5,
      mythic: 1.5,
      ancestral: 2.0,
    },
  },
  {
    id: 'knockbackChance',
    displayName: 'Knockback Chance',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: 2,
      legendary: 4,
      mythic: 6,
      ancestral: 9,
    },
  },
  {
    id: 'knockbackForce',
    displayName: 'Knockback Force',
    moduleType: 'armor',
    values: {
      common: null,
      rare: null,
      epic: 0.1,
      legendary: 0.4,
      mythic: 0.9,
      ancestral: 1.5,
    },
  },
  {
    id: 'orbSpeed',
    displayName: 'Orb Speed',
    moduleType: 'armor',
    values: {
      common: null,
      rare: null,
      epic: 1,
      legendary: 1.5,
      mythic: 2,
      ancestral: 3,
    },
  },
  {
    id: 'orbs',
    displayName: 'Orbs',
    moduleType: 'armor',
    values: {
      common: null,
      rare: null,
      epic: null,
      legendary: null,
      mythic: 1,
      ancestral: 2,
    },
  },
  {
    id: 'shockwaveSize',
    displayName: 'Shockwave Size',
    moduleType: 'armor',
    values: {
      common: null,
      rare: null,
      epic: 0.1,
      legendary: 0.3,
      mythic: 0.7,
      ancestral: 1,
    },
  },
  {
    id: 'shockwaveFrequency',
    displayName: 'Shockwave Frequency',
    moduleType: 'armor',
    unit: 's',
    values: {
      common: null,
      rare: null,
      epic: -1,
      legendary: -2,
      mythic: -3,
      ancestral: -4,
    },
  },
  {
    id: 'landMineDamage',
    displayName: 'Land Mine Damage',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: null,
      rare: 30,
      epic: 50,
      legendary: 150,
      mythic: 500,
      ancestral: 800,
    },
  },
  {
    id: 'landMineChance',
    displayName: 'Land Mine Chance',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: null,
      rare: 1.5,
      epic: 3,
      legendary: 6,
      mythic: 9,
      ancestral: 12,
    },
  },
  {
    id: 'landMineRadius',
    displayName: 'Land Mine Radius',
    moduleType: 'armor',
    values: {
      common: null,
      rare: 0.1,
      epic: 0.15,
      legendary: 0.3,
      mythic: 0.75,
      ancestral: 1,
    },
  },
  {
    id: 'deathDefy',
    displayName: 'Death Defy',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: null,
      legendary: 1.5,
      mythic: 3.5,
      ancestral: 5,
    },
  },
  {
    id: 'wallHealth',
    displayName: 'Wall Health',
    moduleType: 'armor',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: 20,
      legendary: 40,
      mythic: 90,
      ancestral: 120,
    },
  },
  {
    id: 'wallRebuild',
    displayName: 'Wall Rebuild',
    moduleType: 'armor',
    unit: 's',
    values: {
      common: null,
      rare: null,
      epic: -20,
      legendary: -40,
      mythic: -80,
      ancestral: -100,
    },
  },
];
