/**
 * Cannon Sub-Effects (Attack)
 *
 * 19 sub-effects for the Cannon module, focused on damage and critical hits.
 * Data sourced from docs/subeffects.md.
 */

import type { SubEffectConfig } from '../types';

export const CANNON_SUB_EFFECTS: SubEffectConfig[] = [
  {
    id: 'attackSpeed',
    displayName: 'Attack Speed',
    moduleType: 'cannon',
    values: {
      common: 0.3,
      rare: 0.5,
      epic: 0.7,
      legendary: 1,
      mythic: 3,
      ancestral: 5,
    },
  },
  {
    id: 'critChance',
    displayName: 'Crit Chance',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: 2,
      rare: 3,
      epic: 4,
      legendary: 6,
      mythic: 8,
      ancestral: 10,
    },
  },
  {
    id: 'critFactor',
    displayName: 'Crit Factor',
    moduleType: 'cannon',
    unit: 'x',
    values: {
      common: 2,
      rare: 4,
      epic: 6,
      legendary: 8,
      mythic: 12,
      ancestral: 15,
    },
  },
  {
    id: 'attackRange',
    displayName: 'Attack Range',
    moduleType: 'cannon',
    unit: 'm',
    values: {
      common: 2,
      rare: 4,
      epic: 8,
      legendary: 12,
      mythic: 20,
      ancestral: 30,
    },
  },
  {
    id: 'damagePerMeter',
    displayName: 'Damage / Meter',
    moduleType: 'cannon',
    unit: 'x',
    values: {
      common: 0.005,
      rare: 0.01,
      epic: 0.025,
      legendary: 0.04,
      mythic: 0.075,
      ancestral: 0.15,
    },
  },
  {
    id: 'multishotChance',
    displayName: 'Multishot Chance',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: null,
      rare: 3,
      epic: 5,
      legendary: 7,
      mythic: 10,
      ancestral: 13,
    },
  },
  {
    id: 'multishotTargets',
    displayName: 'Multishot Targets',
    moduleType: 'cannon',
    values: {
      common: null,
      rare: null,
      epic: 1,
      legendary: 2,
      mythic: 3,
      ancestral: 4,
    },
  },
  {
    id: 'rapidFireChance',
    displayName: 'Rapid Fire Chance',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: null,
      rare: 2,
      epic: 4,
      legendary: 6,
      mythic: 9,
      ancestral: 12,
    },
  },
  {
    id: 'rapidFireDuration',
    displayName: 'Rapid Fire Duration',
    moduleType: 'cannon',
    unit: 's',
    values: {
      common: null,
      rare: 0.4,
      epic: 0.8,
      legendary: 1.4,
      mythic: 2.5,
      ancestral: 3.5,
    },
  },
  {
    id: 'bounceShotChance',
    displayName: 'Bounce Shot Chance',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: null,
      rare: 2,
      epic: 3,
      legendary: 5,
      mythic: 9,
      ancestral: 12,
    },
  },
  {
    id: 'bounceShotTargets',
    displayName: 'Bounce Shot Targets',
    moduleType: 'cannon',
    values: {
      common: null,
      rare: null,
      epic: 1,
      legendary: 2,
      mythic: 3,
      ancestral: 4,
    },
  },
  {
    id: 'bounceShotRange',
    displayName: 'Bounce Shot Range',
    moduleType: 'cannon',
    unit: 'm',
    values: {
      common: null,
      rare: 0.5,
      epic: 0.8,
      legendary: 1.2,
      mythic: 1.8,
      ancestral: 2.0,
    },
  },
  {
    id: 'superCritChance',
    displayName: 'Super Crit Chance',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: 3,
      legendary: 5,
      mythic: 7,
      ancestral: 10,
    },
  },
  {
    id: 'superCritMulti',
    displayName: 'Super Crit Multi',
    moduleType: 'cannon',
    unit: 'x',
    values: {
      common: null,
      rare: null,
      epic: 2,
      legendary: 3,
      mythic: 5,
      ancestral: 7,
    },
  },
  {
    id: 'rendArmorChance',
    displayName: 'Rend Armor Chance',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: null,
      legendary: 2,
      mythic: 5,
      ancestral: 8,
    },
  },
  {
    id: 'rendArmorMulti',
    displayName: 'Rend Armor Multi',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: null,
      legendary: 2,
      mythic: 5,
      ancestral: 8,
    },
  },
  {
    id: 'maxRendArmorMulti',
    displayName: 'Max Rend Armor Multi',
    moduleType: 'cannon',
    unit: '%',
    values: {
      common: null,
      rare: null,
      epic: null,
      legendary: 200,
      mythic: 300,
      ancestral: 500,
    },
  },
];
