// AUTO-GENERATED by scripts/migration-data-prep/scaffold-v2-to-v3-map.mjs
// Do not hand-edit. Rerun the scaffolding script to regenerate.
//
// Source data:
//   scripts/migration-data-prep/out/v2-field-list.csv
//   scripts/migration-data-prep/out/v28-field-matrix.csv
//   sampleData/v28/*.txt (for "last seen" hints)
//   src/features/game-runs/.../section-config.ts (for "known V27" hints)
//
// This file is the scaffold for diffing. The hand-edited authoritative
// map lives in v2-to-v3-field-map.ts alongside this file; app code
// imports from there, not this one. When inputs change, rerun the
// scaffold and reconcile manually into v2-to-v3-field-map.ts.
//
// Hint legend:
//   "known V27"     -> V2 field appears in the run-details section-config
//                      (was part of the V27 UI). High confidence a V27
//                      meaning exists for it.
//   "not in section-config" -> No V27 UI binding. Either a V28-only
//                      field that leaked through last-write-wins, a V27
//                      field that was only in charts/other views, or a
//                      dead field.
//   "(seen in N/6)" -> How many of the 6 V28 sample exports contained
//                      this section/label pair. Lower counts = less
//                      universal; may be run-type-specific.
//   "[LAST in: X]"  -> In V28 export X, this section/label was the LAST
//                      occurrence of the label. Flat last-write-wins
//                      parsing of that file into V27 storage would
//                      have left this value under the bare V2 key. If
//                      a V2 row has V28-era data, this is the most
//                      likely actual meaning of the bare V2 column.

/**
 * Sentinel for unresolved V2 -> V3 mappings. The hand-edited map must
 * replace every TODO_V2 call with either a real target key or an entry
 * in INTENTIONALLY_DROPPED (intentionally-dropped.ts).
 */
export function TODO_V2(v2FieldName: string): string {
  throw new Error(
    `[V2 migration] unresolved V2 field "${v2FieldName}" - resolve in v2-to-v3-field-map.ts or add to INTENTIONALLY_DROPPED`
  );
}

export const V2_TO_V3_FIELD_MAP_GENERATED: Record<string, string> = {
  'adGems': 'currencies_adGems', // auto (not in section-config; likely V28-only or dropped)
  'amplifyBot': 'killedWithEffectActive_amplifyBot', // auto (not in section-config; likely V28-only or dropped)
  'armorShards': 'currencies_armorShards', // auto (known V27)
  // ambiguous: 2 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_attackChip' (seen in 6/6)
  //   'enemiesHitBy_attackChip' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  'attackChip': TODO_V2('attackChip'),
  'basic': 'totalEnemies_basic', // auto (known V27)
  'battleDate': 'battleReport_battleDate', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 4 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'coins_blackHole' (seen in 6/6)
  //   'damage_blackHole' (seen in 6/6)
  //   'enemiesDestroyedBy_blackHole' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_blackHole' (seen in 6/6)
  'blackHole': TODO_V2('blackHole'),
  'blackHoleDamage': TODO_V2('blackHoleDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'boss': 'totalEnemies_boss', // auto (known V27)
  'bountyCoins': 'coins_bountyCoins', // auto (not in section-config; likely V28-only or dropped)
  'cannonShards': 'currencies_cannonShards', // auto (known V27)
  'cashEarned': 'cash_cashEarned', // auto (known V27)
  'cashFromGoldenTower': TODO_V2('cashFromGoldenTower'), // no V28 candidate (known V27)
  // ambiguous: 2 V28 candidates (known V27)
  //   'battleReport_cellsEarned' (seen in 6/6)
  //   'currencies_cellsEarned' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  'cellsEarned': TODO_V2('cellsEarned'),
  'cellsPerHour': 'battleReport_cellsPerHour', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_chainLightning' (seen in 6/6)
  //   'enemiesDestroyedBy_chainLightning' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_chainLightning' (seen in 6/6)
  'chainLightning': TODO_V2('chainLightning'),
  'chainLightningDamage': TODO_V2('chainLightningDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'chainThunder': 'damageBlocked_chainThunder', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 2 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damageBlocked_chronoField' (seen in 6/6)
  //   'enemiesHitBy_chronoField' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  'chronoField': TODO_V2('chronoField'),
  'coinBonusUpgrade': 'coins_coinBonusUpgrade', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 2 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'battleReport_coinsEarned' (seen in 6/6)
  //   'coins_coinsEarned' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  'coinsEarned': TODO_V2('coinsEarned'),
  'coinsFetched': 'coins_coinsFetched', // auto (not in section-config; likely V28-only or dropped)
  'coinsFromBlackhole': TODO_V2('coinsFromBlackhole'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsFromBlackHole': TODO_V2('coinsFromBlackHole'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsFromCoinBonuses': 'coins_coinsFromCoinBonuses', // auto (not in section-config; likely V28-only or dropped)
  'coinsFromCoinUpgrade': TODO_V2('coinsFromCoinUpgrade'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsFromDeathWave': TODO_V2('coinsFromDeathWave'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsFromGoldenTower': TODO_V2('coinsFromGoldenTower'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsFromOrb': TODO_V2('coinsFromOrb'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsFromOrbs': TODO_V2('coinsFromOrbs'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsFromSpotlight': TODO_V2('coinsFromSpotlight'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsPerHour': 'battleReport_coinsPerHour', // auto (not in section-config; likely V28-only or dropped)
  'coinsStolen': TODO_V2('coinsStolen'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'coinsWave': 'coins_coinsWave', // auto (not in section-config; likely V28-only or dropped)
  'commander': 'totalEnemies_commander', // auto (known V27)
  'commanders': TODO_V2('commanders'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'commonModules': 'currencies_commonModules', // auto (known V27)
  'coreShards': 'currencies_coreShards', // auto (known V27)
  'criticalCoin': 'coins_criticalCoin', // auto (not in section-config; likely V28-only or dropped)
  'damage': TODO_V2('damage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'damageDealt': 'damage_damageDealt', // auto (not in section-config; likely V28-only or dropped)
  'damageGainFromBerserk': TODO_V2('damageGainFromBerserk'), // no V28 candidate (known V27)
  'damageTaken': TODO_V2('damageTaken'), // no V28 candidate (known V27)
  'damageTakenWall': TODO_V2('damageTakenWall'), // no V28 candidate (known V27)
  'damageTakenWhileBerserked': TODO_V2('damageTakenWhileBerserked'), // no V28 candidate (known V27)
  'deathDefy': 'counts_deathDefy', // auto (known V27)
  'deathPenalty': 'killedWithEffectActive_deathPenalty', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_deathRay' (seen in 6/6)
  //   'enemiesDestroyedBy_deathRay' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_deathRay' (seen in 6/6)
  'deathRay': TODO_V2('deathRay'),
  'deathRayDamage': TODO_V2('deathRayDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  // ambiguous: 4 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'coins_deathWave' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'damage_deathWave' (seen in 6/6)
  //   'enemiesHitBy_deathWave' (seen in 6/6)
  //   'killedWithEffectActive_deathWave' (seen in 6/6)
  'deathWave': TODO_V2('deathWave'),
  'deathWaveDamage': TODO_V2('deathWaveDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'defense': 'damageBlocked_defense', // auto (not in section-config; likely V28-only or dropped)
  'defenseAbsolute': 'damageBlocked_defenseAbsolute', // auto (not in section-config; likely V28-only or dropped)
  'demonMode': 'counts_demonMode', // auto (not in section-config; likely V28-only or dropped)
  'destroyedByDeathRay': TODO_V2('destroyedByDeathRay'), // no V28 candidate (known V27)
  'destroyedByLandMine': TODO_V2('destroyedByLandMine'), // no V28 candidate (known V27)
  'destroyedByOrbs': TODO_V2('destroyedByOrbs'), // no V28 candidate (known V27)
  'destroyedByThorns': TODO_V2('destroyedByThorns'), // no V28 candidate (known V27)
  'destroyedInGoldenBot': TODO_V2('destroyedInGoldenBot'), // no V28 candidate (known V27)
  'destroyedInSpotlight': TODO_V2('destroyedInSpotlight'), // no V28 candidate (known V27)
  'electrons': 'damage_electrons', // auto (not in section-config; likely V28-only or dropped)
  'electronsDamage': TODO_V2('electronsDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'enemiesHitByOrbs': TODO_V2('enemiesHitByOrbs'), // no V28 candidate (known V27)
  'enemyAttackLevelsSkipped': 'utility_enemyAttackLevelsSkipped', // auto (not in section-config; likely V28-only or dropped)
  'enemyHealthLevelsSkipped': 'utility_enemyHealthLevelsSkipped', // auto (not in section-config; likely V28-only or dropped)
  'fast': 'totalEnemies_fast', // auto (known V27)
  'fetchGems': 'currencies_fetchGems', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 4 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_flameBot' (seen in 6/6)
  //   'damageBlocked_flameBot' (seen in 6/6)
  //   'enemiesDestroyedBy_flameBot' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_flameBot' (seen in 6/6)
  'flameBot': TODO_V2('flameBot'),
  'flameBotDamage': TODO_V2('flameBotDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'freeAttackUpgrade': 'utility_freeAttackUpgrade', // auto (known V27)
  'freeDefenseUpgrade': 'utility_freeDefenseUpgrade', // auto (known V27)
  'freeUtilityUpgrade': 'utility_freeUtilityUpgrade', // auto (known V27)
  'fromDeathWave': 'bonusHealthGained_fromDeathWave', // auto (not in section-config; likely V28-only or dropped)
  'gameTime': 'battleReport_gameTime', // auto (known V27)
  'gemBlocksTapped': 'currencies_gemBlocksTapped', // auto (known V27)
  'gems': 'currencies_gems', // auto (known V27)
  'generatorShards': 'currencies_generatorShards', // auto (known V27)
  // ambiguous: 2 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'coins_goldenBot' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'killedWithEffectActive_goldenBot' (seen in 6/6)
  'goldenBot': TODO_V2('goldenBot'),
  'goldenBotCoinsEarned': TODO_V2('goldenBotCoinsEarned'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'goldenCombo': 'coins_goldenCombo', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'cash_goldenTower' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'coins_goldenTower' (seen in 6/6)
  //   'killedWithEffectActive_goldenTower' (seen in 6/6)
  'goldenTower': TODO_V2('goldenTower'),
  'guardianCatches': TODO_V2('guardianCatches'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'guardianCoinsStolen': TODO_V2('guardianCoinsStolen'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'highestCoinsMinute': 'records_highestCoinsMinute', // auto (not in section-config; likely V28-only or dropped)
  'hitsAbsorbedByEnergyShield': 'counts_hitsAbsorbedByEnergyShield', // auto (not in section-config; likely V28-only or dropped)
  'hpFromDeathWave': TODO_V2('hpFromDeathWave'), // no V28 candidate (known V27)
  'innerLandMineDamage': TODO_V2('innerLandMineDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_innerLandMines' (seen in 6/6)
  //   'enemiesDestroyedBy_innerLandMines' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_innerLandMines' (seen in 6/6)
  'innerLandMines': TODO_V2('innerLandMines'),
  'interestEarned': 'cash_interestEarned', // auto (known V27)
  'killedBy': 'battleReport_killedBy', // auto (known V27)
  'landMineDamage': TODO_V2('landMineDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_landMines' (seen in 6/6)
  //   'enemiesDestroyedBy_landMines' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_landMines' (seen in 6/6)
  'landMines': TODO_V2('landMines'),
  'landMinesSpawned': 'counts_landMinesSpawned', // auto (known V27)
  'largestGoldenCombo': 'records_largestGoldenCombo', // auto (not in section-config; likely V28-only or dropped)
  'largestInnerLandmineCharge': 'records_largestInnerLandmineCharge', // auto (not in section-config; likely V28-only or dropped)
  'largestSmartMissileStack': 'records_largestSmartMissileStack', // auto (not in section-config; likely V28-only or dropped)
  'largestWaveSkip': 'records_largestWaveSkip', // auto (not in section-config; likely V28-only or dropped)
  'lifesteal': 'healthRegenerated_lifesteal', // auto (not in section-config; likely V28-only or dropped)
  'medals': 'currencies_medals', // auto (known V27)
  'mostCellsFromWaveSkip': 'records_mostCellsFromWaveSkip', // auto (not in section-config; likely V28-only or dropped)
  'mostCoinsFromGoldenCombo': 'records_mostCoinsFromGoldenCombo', // auto (not in section-config; likely V28-only or dropped)
  'mostCoinsFromWaveSkip': 'records_mostCoinsFromWaveSkip', // auto (not in section-config; likely V28-only or dropped)
  'negativeMassProjector': 'damageBlocked_negativeMassProjector', // auto (not in section-config; likely V28-only or dropped)
  'nuke': 'counts_nuke', // auto (not in section-config; likely V28-only or dropped)
  'orbDamage': TODO_V2('orbDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'orbHits': TODO_V2('orbHits'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'orbitalAugment': 'enemiesHitBy_orbitalAugment', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 4 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'coins_orbs' (seen in 6/6)
  //   'damage_orbs' (seen in 6/6)
  //   'enemiesDestroyedBy_orbs' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_orbs' (seen in 6/6)
  'orbs': TODO_V2('orbs'),
  'other': 'enemiesDestroyedBy_other', // auto (not in section-config; likely V28-only or dropped)
  'overcharge': 'totalEnemies_overcharge', // auto (known V27)
  'overcharges': TODO_V2('overcharges'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_poisonSwamp' (seen in 6/6)
  //   'enemiesDestroyedBy_poisonSwamp' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_poisonSwamp' (seen in 6/6)
  'poisonSwamp': TODO_V2('poisonSwamp'),
  'primordialCollapse': 'damageBlocked_primordialCollapse', // auto (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_projectiles' (seen in 6/6)
  //   'enemiesDestroyedBy_projectiles' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_projectiles' (seen in 6/6)
  'projectiles': TODO_V2('projectiles'),
  'projectilesCount': 'counts_projectilesCount', // auto (known V27)
  'projectilesDamage': TODO_V2('projectilesDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'protector': 'totalEnemies_protector', // auto (known V27)
  'ranged': 'totalEnemies_ranged', // auto (known V27)
  'rareModules': 'currencies_rareModules', // auto (known V27)
  'rays': 'totalEnemies_rays', // auto (known V27)
  'realTime': 'battleReport_realTime', // auto (known V27)
  'recoveryPackages': 'utility_recoveryPackages', // auto (known V27)
  'rendArmor': 'damage_rendArmor', // auto (not in section-config; likely V28-only or dropped)
  'rendArmorDamage': TODO_V2('rendArmorDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'rerollShards': TODO_V2('rerollShards'), // no V28 candidate (known V27)
  'rerollShardsEarned': 'currencies_rerollShardsEarned', // auto (known V27)
  'rerollShardsFetched': 'currencies_rerollShardsFetched', // auto (not in section-config; likely V28-only or dropped)
  'saboteur': 'totalEnemies_saboteur', // auto (known V27)
  'saboteurs': TODO_V2('saboteurs'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'scatters': 'totalEnemies_scatters', // auto (known V27)
  'secondWind': 'counts_secondWind', // auto (not in section-config; likely V28-only or dropped)
  'smartMissileDamage': TODO_V2('smartMissileDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_smartMissiles' (seen in 6/6)
  //   'enemiesDestroyedBy_smartMissiles' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_smartMissiles' (seen in 6/6)
  'smartMissiles': TODO_V2('smartMissiles'),
  // ambiguous: 2 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'coins_spotlight' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'killedWithEffectActive_spotlight' (seen in 6/6)
  'spotlight': TODO_V2('spotlight'),
  'summonedEnemies': 'totalEnemies_summonedEnemies', // auto (known V27)
  'swampDamage': TODO_V2('swampDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'taggedByDeathwave': TODO_V2('taggedByDeathwave'), // no V28 candidate (known V27)
  'taggedByDeathWave': TODO_V2('taggedByDeathWave'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  'tank': 'totalEnemies_tank', // auto (known V27)
  'thornDamage': TODO_V2('thornDamage'), // no V28 candidate (not in section-config; likely V28-only or dropped)
  // ambiguous: 3 V28 candidates (not in section-config; likely V28-only or dropped)
  //   'damage_thorns' (seen in 6/6)
  //   'enemiesDestroyedBy_thorns' (seen in 6/6) [LAST in: Dissonance_Attack_2026-04-09, Dissonance_Defense_2026-04-09, Dissonance_UltimateWeapons_2026-04-09, Dissonance_Utility_2026-04-10, Farming_2026-04-11, Tournament_2026-04-10]
  //   'enemiesHitBy_thorns' (seen in 6/6)
  'thorns': TODO_V2('thorns'),
  'thunderBot': 'enemiesHitBy_thunderBot', // auto (not in section-config; likely V28-only or dropped)
  'thunderBotStuns': 'counts_thunderBotStuns', // auto (known V27)
  'tier': 'battleReport_tier', // auto (known V27)
  'totalElites': TODO_V2('totalElites'), // no V28 candidate (known V27)
  'totalEnemies': 'totalEnemies_totalEnemies', // auto (not in section-config; likely V28-only or dropped)
  'tower': 'damageTaken_tower', // auto (not in section-config; likely V28-only or dropped)
  'towerHealthRegen': 'healthRegenerated_towerHealthRegen', // auto (not in section-config; likely V28-only or dropped)
  'vampires': 'totalEnemies_vampires', // auto (known V27)
  'wall': 'damageTaken_wall', // auto (not in section-config; likely V28-only or dropped)
  'wallHealthRegen': 'healthRegenerated_wallHealthRegen', // auto (not in section-config; likely V28-only or dropped)
  'wave': 'battleReport_wave', // auto (known V27)
  'waveSkip': 'coins_waveSkip', // auto (not in section-config; likely V28-only or dropped)
  'wavesSkipped': 'counts_wavesSkipped', // auto (known V27)
};
