import { test as base, Page } from '@playwright/test';
import { loadLocalStorageFromSeedFiles, injectLocalStorage } from '../helpers/seed-storage';

/**
 * Seeded Page Fixture
 *
 * Extends Playwright's base test with a pre-seeded page fixture.
 * This fixture loads localStorage data from seed files (generated by the seed project)
 * and injects it into the browser before navigating to the application.
 *
 * Usage:
 *   import { test, expect } from '../fixtures/seeded-page';
 *
 *   test('my test with seeded data', async ({ seededPage }) => {
 *     await seededPage.goto('/');
 *     // localStorage is already populated with seed data
 *   });
 *
 * Note: The seed project (bulk-import.spec.ts) must run first to generate seed files.
 * This is enforced by the Playwright config's project dependencies.
 */

type SeededPageFixtures = {
  seededPage: Page;
};

export const test = base.extend<SeededPageFixtures>({
  seededPage: async ({ page, baseURL }, use) => {
    // Load seed data from files
    const seedData = await loadLocalStorageFromSeedFiles();

    // Navigate to base URL first (required for localStorage to work)
    await page.goto(baseURL || 'http://localhost:3000');

    // Inject localStorage data
    await injectLocalStorage(page, seedData);

    // Reload to ensure application picks up seeded data
    await page.reload();

    // Provide seeded page to test
    await use(page);

    // Cleanup (if needed) happens automatically
  },
});

export { expect } from '@playwright/test';
