import { edge } from '../../../builders';
import type { Edge } from '../../../types';
import * as f from '../../fields.nodes';
import {
  SECTION_BATTLE_REPORT_NODE,
  SECTION_BONUS_HEALTH_GAINED_NODE,
  SECTION_CASH_NODE,
  SECTION_COINS_NODE,
  SECTION_COUNTS_NODE,
  SECTION_CURRENCIES_NODE,
  SECTION_DAMAGE_BLOCKED_NODE,
  SECTION_DAMAGE_NODE,
  SECTION_DAMAGE_TAKEN_NODE,
  SECTION_ENEMIES_DESTROYED_BY_NODE,
  SECTION_ENEMIES_HIT_BY_NODE,
  SECTION_HEALTH_REGENERATED_NODE,
  SECTION_KILLED_WITH_EFFECT_ACTIVE_NODE,
  SECTION_RECORDS_NODE,
  SECTION_TOTAL_ENEMIES_NODE,
  SECTION_UTILITY_NODE,
} from '../../sections.nodes';

// Field → Section membership. Sections align 1:1 with V3 storage prefixes.
// Declaration order within each section is the run-details display order.
// Internal fields (`_date`, `_time`, `_notes`, `_runType`, `_rank`) have no
// section membership — they're app-managed metadata, not game-export data.
//
// Field nodes are imported as `* as f` for the same reason `renames.edges.ts`
// does it: keeps the file under the project's max-lines threshold without
// abandoning the locked refactor-safe `*_NODE` convention.

function membership(sectionId: string, fieldIds: readonly string[]): readonly Edge[] {
  return fieldIds.map((fieldId) => edge(fieldId, 'BELONGS_TO_SECTION', sectionId));
}

export const BELONGS_TO_SECTION_EDGES: readonly Edge[] = [
  ...membership(SECTION_BATTLE_REPORT_NODE.id, [
    f.BATTLE_REPORT__TIER_NODE.id,
    f.BATTLE_REPORT__WAVE_NODE.id,
    f.BATTLE_REPORT__KILLED_BY_NODE.id,
    f.BATTLE_REPORT__GAME_TIME_NODE.id,
    f.BATTLE_REPORT__REAL_TIME_NODE.id,
    f.BATTLE_REPORT__BATTLE_DATE_NODE.id,
    f.BATTLE_REPORT__COINS_EARNED_NODE.id,
    f.BATTLE_REPORT__COINS_PER_HOUR_NODE.id,
    f.BATTLE_REPORT__CELLS_EARNED_NODE.id,
    f.BATTLE_REPORT__CELLS_PER_HOUR_NODE.id,
  ]),
  ...membership(SECTION_COUNTS_NODE.id, [
    f.COUNTS__WAVES_SKIPPED_NODE.id,
    f.COUNTS__DEATH_DEFY_NODE.id,
    f.COUNTS__SECOND_WIND_NODE.id,
    f.COUNTS__DEMON_MODE_NODE.id,
    f.COUNTS__NUKE_NODE.id,
    f.COUNTS__HITS_ABSORBED_BY_ENERGY_SHIELD_NODE.id,
    f.COUNTS__PROJECTILES_COUNT_NODE.id,
    f.COUNTS__LAND_MINES_SPAWNED_NODE.id,
    f.COUNTS__THUNDER_BOT_STUNS_NODE.id,
  ]),
  ...membership(SECTION_UTILITY_NODE.id, [
    f.UTILITY__FREE_ATTACK_UPGRADE_NODE.id,
    f.UTILITY__FREE_DEFENSE_UPGRADE_NODE.id,
    f.UTILITY__FREE_UTILITY_UPGRADE_NODE.id,
    f.UTILITY__RECOVERY_PACKAGES_NODE.id,
    f.UTILITY__ENEMY_ATTACK_LEVELS_SKIPPED_NODE.id,
    f.UTILITY__ENEMY_HEALTH_LEVELS_SKIPPED_NODE.id,
  ]),
  ...membership(SECTION_RECORDS_NODE.id, [
    f.RECORDS__HIGHEST_COINS_MINUTE_NODE.id,
    f.RECORDS__LARGEST_WAVE_SKIP_NODE.id,
    f.RECORDS__MOST_COINS_FROM_WAVE_SKIP_NODE.id,
    f.RECORDS__MOST_CELLS_FROM_WAVE_SKIP_NODE.id,
    f.RECORDS__LARGEST_GOLDEN_COMBO_NODE.id,
    f.RECORDS__MOST_COINS_FROM_GOLDEN_COMBO_NODE.id,
    f.RECORDS__LARGEST_SMART_MISSILE_STACK_NODE.id,
    f.RECORDS__LARGEST_INNER_LANDMINE_CHARGE_NODE.id,
  ]),
  ...membership(SECTION_DAMAGE_NODE.id, [
    f.DAMAGE__DAMAGE_DEALT_NODE.id,
    f.DAMAGE__DEATH_WAVE_NODE.id,
    f.DAMAGE__CHAIN_LIGHTNING_NODE.id,
    f.DAMAGE__THORNS_NODE.id,
    f.DAMAGE__ORBS_NODE.id,
    f.DAMAGE__FLAME_BOT_NODE.id,
    f.DAMAGE__LAND_MINES_NODE.id,
    f.DAMAGE__DEATH_RAY_NODE.id,
    f.DAMAGE__SMART_MISSILES_NODE.id,
    f.DAMAGE__INNER_LAND_MINES_NODE.id,
    f.DAMAGE__POISON_SWAMP_NODE.id,
    f.DAMAGE__BLACK_HOLE_NODE.id,
    f.DAMAGE__ELECTRONS_NODE.id,
    f.DAMAGE__PROJECTILES_NODE.id,
    f.DAMAGE__REND_ARMOR_NODE.id,
    f.DAMAGE__ATTACK_CHIP_NODE.id,
  ]),
  ...membership(SECTION_DAMAGE_TAKEN_NODE.id, [
    f.DAMAGE_TAKEN__TOWER_NODE.id,
    f.DAMAGE_TAKEN__WALL_NODE.id,
  ]),
  ...membership(SECTION_BONUS_HEALTH_GAINED_NODE.id, [
    f.BONUS_HEALTH_GAINED__FROM_DEATH_WAVE_NODE.id,
  ]),
  ...membership(SECTION_HEALTH_REGENERATED_NODE.id, [
    f.HEALTH_REGENERATED__TOWER_HEALTH_REGEN_NODE.id,
    f.HEALTH_REGENERATED__WALL_HEALTH_REGEN_NODE.id,
    f.HEALTH_REGENERATED__LIFESTEAL_NODE.id,
  ]),
  ...membership(SECTION_DAMAGE_BLOCKED_NODE.id, [
    f.DAMAGE_BLOCKED__DEFENSE_NODE.id,
    f.DAMAGE_BLOCKED__DEFENSE_ABSOLUTE_NODE.id,
    f.DAMAGE_BLOCKED__CHRONO_FIELD_NODE.id,
    f.DAMAGE_BLOCKED__CHAIN_THUNDER_NODE.id,
    f.DAMAGE_BLOCKED__PRIMORDIAL_COLLAPSE_NODE.id,
    f.DAMAGE_BLOCKED__NEGATIVE_MASS_PROJECTOR_NODE.id,
    f.DAMAGE_BLOCKED__FLAME_BOT_NODE.id,
  ]),
  ...membership(SECTION_ENEMIES_HIT_BY_NODE.id, [
    f.ENEMIES_HIT_BY__PROJECTILES_NODE.id,
    f.ENEMIES_HIT_BY__THORNS_NODE.id,
    f.ENEMIES_HIT_BY__ORBS_NODE.id,
    f.ENEMIES_HIT_BY__DEATH_RAY_NODE.id,
    f.ENEMIES_HIT_BY__CHAIN_LIGHTNING_NODE.id,
    f.ENEMIES_HIT_BY__SMART_MISSILES_NODE.id,
    f.ENEMIES_HIT_BY__INNER_LAND_MINES_NODE.id,
    f.ENEMIES_HIT_BY__POISON_SWAMP_NODE.id,
    f.ENEMIES_HIT_BY__DEATH_WAVE_NODE.id,
    f.ENEMIES_HIT_BY__BLACK_HOLE_NODE.id,
    f.ENEMIES_HIT_BY__FLAME_BOT_NODE.id,
    f.ENEMIES_HIT_BY__ATTACK_CHIP_NODE.id,
    f.ENEMIES_HIT_BY__LAND_MINES_NODE.id,
    f.ENEMIES_HIT_BY__CHRONO_FIELD_NODE.id,
    f.ENEMIES_HIT_BY__ORBITAL_AUGMENT_NODE.id,
    f.ENEMIES_HIT_BY__THUNDER_BOT_NODE.id,
  ]),
  ...membership(SECTION_KILLED_WITH_EFFECT_ACTIVE_NODE.id, [
    f.KILLED_WITH_EFFECT_ACTIVE__SPOTLIGHT_NODE.id,
    f.KILLED_WITH_EFFECT_ACTIVE__DEATH_WAVE_NODE.id,
    f.KILLED_WITH_EFFECT_ACTIVE__GOLDEN_BOT_NODE.id,
    f.KILLED_WITH_EFFECT_ACTIVE__GOLDEN_TOWER_NODE.id,
    f.KILLED_WITH_EFFECT_ACTIVE__AMPLIFY_BOT_NODE.id,
    f.KILLED_WITH_EFFECT_ACTIVE__DEATH_PENALTY_NODE.id,
    // Multi-section: `totalEnemies_summonedEnemies` also lives in
    // section:totalEnemies (per V3 storage prefix). It renders in the
    // killedWithEffectActive supplementary breakdown alongside the
    // killedWithEffectActive_* fields. The `IS_MEASURED_AGAINST` edge to
    // `totalEnemies_totalEnemies` is declared in
    // `../sources/sources.measured-against.edges.ts`.
    f.TOTAL_ENEMIES__SUMMONED_ENEMIES_NODE.id,
  ]),
  ...membership(SECTION_TOTAL_ENEMIES_NODE.id, [
    f.TOTAL_ENEMIES__TOTAL_ENEMIES_NODE.id,
    f.TOTAL_ENEMIES__BASIC_NODE.id,
    f.TOTAL_ENEMIES__FAST_NODE.id,
    f.TOTAL_ENEMIES__TANK_NODE.id,
    f.TOTAL_ENEMIES__RANGED_NODE.id,
    f.TOTAL_ENEMIES__BOSS_NODE.id,
    f.TOTAL_ENEMIES__PROTECTOR_NODE.id,
    f.TOTAL_ENEMIES__VAMPIRES_NODE.id,
    f.TOTAL_ENEMIES__RAYS_NODE.id,
    f.TOTAL_ENEMIES__SCATTERS_NODE.id,
    f.TOTAL_ENEMIES__SABOTEUR_NODE.id,
    f.TOTAL_ENEMIES__COMMANDER_NODE.id,
    f.TOTAL_ENEMIES__OVERCHARGE_NODE.id,
    f.TOTAL_ENEMIES__SUMMONED_ENEMIES_NODE.id,
  ]),
  ...membership(SECTION_ENEMIES_DESTROYED_BY_NODE.id, [
    f.ENEMIES_DESTROYED_BY__ORBS_NODE.id,
    f.ENEMIES_DESTROYED_BY__THORNS_NODE.id,
    f.ENEMIES_DESTROYED_BY__DEATH_RAY_NODE.id,
    f.ENEMIES_DESTROYED_BY__LAND_MINES_NODE.id,
    f.ENEMIES_DESTROYED_BY__INNER_LAND_MINES_NODE.id,
    f.ENEMIES_DESTROYED_BY__BLACK_HOLE_NODE.id,
    f.ENEMIES_DESTROYED_BY__CHAIN_LIGHTNING_NODE.id,
    f.ENEMIES_DESTROYED_BY__FLAME_BOT_NODE.id,
    f.ENEMIES_DESTROYED_BY__POISON_SWAMP_NODE.id,
    f.ENEMIES_DESTROYED_BY__PROJECTILES_NODE.id,
    f.ENEMIES_DESTROYED_BY__SMART_MISSILES_NODE.id,
    f.ENEMIES_DESTROYED_BY__OTHER_NODE.id,
  ]),
  ...membership(SECTION_COINS_NODE.id, [
    f.COINS__COINS_EARNED_NODE.id,
    f.COINS__DEATH_WAVE_NODE.id,
    f.COINS__GOLDEN_TOWER_NODE.id,
    f.COINS__SPOTLIGHT_NODE.id,
    f.COINS__GOLDEN_BOT_NODE.id,
    f.COINS__COINS_FETCHED_NODE.id,
    f.COINS__BLACK_HOLE_NODE.id,
    f.COINS__COIN_BONUS_UPGRADE_NODE.id,
    f.COINS__COINS_FROM_COIN_BONUSES_NODE.id,
    f.COINS__ORBS_NODE.id,
    f.COINS__GOLDEN_COMBO_NODE.id,
    f.COINS__BOUNTY_COINS_NODE.id,
    f.COINS__CRITICAL_COIN_NODE.id,
    f.COINS__WAVE_SKIP_NODE.id,
    f.COINS__COINS_WAVE_NODE.id,
  ]),
  ...membership(SECTION_CASH_NODE.id, [
    f.CASH__CASH_EARNED_NODE.id,
    f.CASH__INTEREST_EARNED_NODE.id,
    f.CASH__GOLDEN_TOWER_NODE.id,
  ]),
  ...membership(SECTION_CURRENCIES_NODE.id, [
    f.CURRENCIES__CELLS_EARNED_NODE.id,
    f.CURRENCIES__MEDALS_NODE.id,
    f.CURRENCIES__GEMS_NODE.id,
    f.CURRENCIES__AD_GEMS_NODE.id,
    f.CURRENCIES__FETCH_GEMS_NODE.id,
    f.CURRENCIES__GEM_BLOCKS_TAPPED_NODE.id,
    f.CURRENCIES__ARMOR_SHARDS_NODE.id,
    f.CURRENCIES__CORE_SHARDS_NODE.id,
    f.CURRENCIES__CANNON_SHARDS_NODE.id,
    f.CURRENCIES__GENERATOR_SHARDS_NODE.id,
    f.CURRENCIES__REROLL_SHARDS_EARNED_NODE.id,
    f.CURRENCIES__REROLL_SHARDS_FETCHED_NODE.id,
    f.CURRENCIES__COMMON_MODULES_NODE.id,
    f.CURRENCIES__RARE_MODULES_NODE.id,
  ]),
];
