import { edge } from '../../../builders';
import type { Edge } from '../../../types';
import {
  CATEGORY_COMBAT_NODE,
  CATEGORY_ECONOMIC_NODE,
  CATEGORY_GENERAL_NODE,
  CATEGORY_RECORDS_NODE,
} from '../../categories.nodes';
import {
  SECTION_BATTLE_REPORT_NODE,
  SECTION_BONUS_HEALTH_GAINED_NODE,
  SECTION_CASH_NODE,
  SECTION_COINS_NODE,
  SECTION_COUNTS_NODE,
  SECTION_CURRENCIES_NODE,
  SECTION_DAMAGE_BLOCKED_NODE,
  SECTION_DAMAGE_NODE,
  SECTION_DAMAGE_TAKEN_NODE,
  SECTION_ENEMIES_DESTROYED_BY_NODE,
  SECTION_ENEMIES_HIT_BY_NODE,
  SECTION_HEALTH_REGENERATED_NODE,
  SECTION_KILLED_WITH_EFFECT_ACTIVE_NODE,
  SECTION_RECORDS_NODE,
  SECTION_TOTAL_ENEMIES_NODE,
  SECTION_UTILITY_NODE,
} from '../../sections.nodes';
import { BELONGS_TO_SECTION_EDGES } from './sections.belongs-to-section.edges';

// Section → Category. Declaration order within each category determines
// run-details section display order. Category order itself is determined
// by declaration order in `categories.nodes.ts`.
const BELONGS_TO_CATEGORY_EDGES: readonly Edge[] = [
  // General
  edge(SECTION_BATTLE_REPORT_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_GENERAL_NODE.id),
  edge(SECTION_COUNTS_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_GENERAL_NODE.id),
  edge(SECTION_UTILITY_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_GENERAL_NODE.id),

  // Records
  edge(SECTION_RECORDS_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_RECORDS_NODE.id),

  // Combat
  edge(SECTION_DAMAGE_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_DAMAGE_TAKEN_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_BONUS_HEALTH_GAINED_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_HEALTH_REGENERATED_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_DAMAGE_BLOCKED_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_ENEMIES_HIT_BY_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_KILLED_WITH_EFFECT_ACTIVE_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_TOTAL_ENEMIES_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),
  edge(SECTION_ENEMIES_DESTROYED_BY_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_COMBAT_NODE.id),

  // Economic
  edge(SECTION_COINS_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_ECONOMIC_NODE.id),
  edge(SECTION_CASH_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_ECONOMIC_NODE.id),
  edge(SECTION_CURRENCIES_NODE.id, 'BELONGS_TO_CATEGORY', CATEGORY_ECONOMIC_NODE.id),
];

export const SECTION_EDGES: readonly Edge[] = [
  ...BELONGS_TO_SECTION_EDGES,
  ...BELONGS_TO_CATEGORY_EDGES,
];
