/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ChartsIndexRouteImport } from './routes/charts/index'
import { Route as SettingsLocaleRouteImport } from './routes/settings/locale'
import { Route as SettingsImportRouteImport } from './routes/settings/import'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsDeleteRouteImport } from './routes/settings/delete'
import { Route as RunsTournamentRouteImport } from './routes/runs/tournament'
import { Route as RunsMilestoneRouteImport } from './routes/runs/milestone'
import { Route as RunsFarmRouteImport } from './routes/runs/farm'
import { Route as ChartsTierTrendsRouteImport } from './routes/charts/tier-trends'
import { Route as ChartsTierStatsRouteImport } from './routes/charts/tier-stats'
import { Route as ChartsSourcesRouteImport } from './routes/charts/sources'
import { Route as ChartsFieldsRouteImport } from './routes/charts/fields'
import { Route as ChartsDeathsRouteImport } from './routes/charts/deaths'
import { Route as ChartsCoverageRouteImport } from './routes/charts/coverage'
import { Route as ChartsCoinsRouteImport } from './routes/charts/coins'
import { Route as ChartsCellsRouteImport } from './routes/charts/cells'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRoute,
} as any)
const ChartsIndexRoute = ChartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChartsRoute,
} as any)
const SettingsLocaleRoute = SettingsLocaleRouteImport.update({
  id: '/locale',
  path: '/locale',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDeleteRoute = SettingsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => SettingsRoute,
} as any)
const RunsTournamentRoute = RunsTournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => RunsRoute,
} as any)
const RunsMilestoneRoute = RunsMilestoneRouteImport.update({
  id: '/milestone',
  path: '/milestone',
  getParentRoute: () => RunsRoute,
} as any)
const RunsFarmRoute = RunsFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => RunsRoute,
} as any)
const ChartsTierTrendsRoute = ChartsTierTrendsRouteImport.update({
  id: '/tier-trends',
  path: '/tier-trends',
  getParentRoute: () => ChartsRoute,
} as any)
const ChartsTierStatsRoute = ChartsTierStatsRouteImport.update({
  id: '/tier-stats',
  path: '/tier-stats',
  getParentRoute: () => ChartsRoute,
} as any)
const ChartsSourcesRoute = ChartsSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => ChartsRoute,
} as any)
const ChartsFieldsRoute = ChartsFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => ChartsRoute,
} as any)
const ChartsDeathsRoute = ChartsDeathsRouteImport.update({
  id: '/deaths',
  path: '/deaths',
  getParentRoute: () => ChartsRoute,
} as any)
const ChartsCoverageRoute = ChartsCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => ChartsRoute,
} as any)
const ChartsCoinsRoute = ChartsCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => ChartsRoute,
} as any)
const ChartsCellsRoute = ChartsCellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => ChartsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/charts/cells': typeof ChartsCellsRoute
  '/charts/coins': typeof ChartsCoinsRoute
  '/charts/coverage': typeof ChartsCoverageRoute
  '/charts/deaths': typeof ChartsDeathsRoute
  '/charts/fields': typeof ChartsFieldsRoute
  '/charts/sources': typeof ChartsSourcesRoute
  '/charts/tier-stats': typeof ChartsTierStatsRoute
  '/charts/tier-trends': typeof ChartsTierTrendsRoute
  '/runs/farm': typeof RunsFarmRoute
  '/runs/milestone': typeof RunsMilestoneRoute
  '/runs/tournament': typeof RunsTournamentRoute
  '/settings/delete': typeof SettingsDeleteRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/locale': typeof SettingsLocaleRoute
  '/charts/': typeof ChartsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts/cells': typeof ChartsCellsRoute
  '/charts/coins': typeof ChartsCoinsRoute
  '/charts/coverage': typeof ChartsCoverageRoute
  '/charts/deaths': typeof ChartsDeathsRoute
  '/charts/fields': typeof ChartsFieldsRoute
  '/charts/sources': typeof ChartsSourcesRoute
  '/charts/tier-stats': typeof ChartsTierStatsRoute
  '/charts/tier-trends': typeof ChartsTierTrendsRoute
  '/runs/farm': typeof RunsFarmRoute
  '/runs/milestone': typeof RunsMilestoneRoute
  '/runs/tournament': typeof RunsTournamentRoute
  '/settings/delete': typeof SettingsDeleteRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/locale': typeof SettingsLocaleRoute
  '/charts': typeof ChartsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charts': typeof ChartsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/charts/cells': typeof ChartsCellsRoute
  '/charts/coins': typeof ChartsCoinsRoute
  '/charts/coverage': typeof ChartsCoverageRoute
  '/charts/deaths': typeof ChartsDeathsRoute
  '/charts/fields': typeof ChartsFieldsRoute
  '/charts/sources': typeof ChartsSourcesRoute
  '/charts/tier-stats': typeof ChartsTierStatsRoute
  '/charts/tier-trends': typeof ChartsTierTrendsRoute
  '/runs/farm': typeof RunsFarmRoute
  '/runs/milestone': typeof RunsMilestoneRoute
  '/runs/tournament': typeof RunsTournamentRoute
  '/settings/delete': typeof SettingsDeleteRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/locale': typeof SettingsLocaleRoute
  '/charts/': typeof ChartsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charts'
    | '/runs'
    | '/settings'
    | '/charts/cells'
    | '/charts/coins'
    | '/charts/coverage'
    | '/charts/deaths'
    | '/charts/fields'
    | '/charts/sources'
    | '/charts/tier-stats'
    | '/charts/tier-trends'
    | '/runs/farm'
    | '/runs/milestone'
    | '/runs/tournament'
    | '/settings/delete'
    | '/settings/export'
    | '/settings/import'
    | '/settings/locale'
    | '/charts/'
    | '/runs/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts/cells'
    | '/charts/coins'
    | '/charts/coverage'
    | '/charts/deaths'
    | '/charts/fields'
    | '/charts/sources'
    | '/charts/tier-stats'
    | '/charts/tier-trends'
    | '/runs/farm'
    | '/runs/milestone'
    | '/runs/tournament'
    | '/settings/delete'
    | '/settings/export'
    | '/settings/import'
    | '/settings/locale'
    | '/charts'
    | '/runs'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/charts'
    | '/runs'
    | '/settings'
    | '/charts/cells'
    | '/charts/coins'
    | '/charts/coverage'
    | '/charts/deaths'
    | '/charts/fields'
    | '/charts/sources'
    | '/charts/tier-stats'
    | '/charts/tier-trends'
    | '/runs/farm'
    | '/runs/milestone'
    | '/runs/tournament'
    | '/settings/delete'
    | '/settings/export'
    | '/settings/import'
    | '/settings/locale'
    | '/charts/'
    | '/runs/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsRoute: typeof ChartsRouteWithChildren
  RunsRoute: typeof RunsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof RunsRoute
    }
    '/charts/': {
      id: '/charts/'
      path: '/'
      fullPath: '/charts/'
      preLoaderRoute: typeof ChartsIndexRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/settings/locale': {
      id: '/settings/locale'
      path: '/locale'
      fullPath: '/settings/locale'
      preLoaderRoute: typeof SettingsLocaleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/import': {
      id: '/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsImportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/delete': {
      id: '/settings/delete'
      path: '/delete'
      fullPath: '/settings/delete'
      preLoaderRoute: typeof SettingsDeleteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/runs/tournament': {
      id: '/runs/tournament'
      path: '/tournament'
      fullPath: '/runs/tournament'
      preLoaderRoute: typeof RunsTournamentRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/milestone': {
      id: '/runs/milestone'
      path: '/milestone'
      fullPath: '/runs/milestone'
      preLoaderRoute: typeof RunsMilestoneRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/farm': {
      id: '/runs/farm'
      path: '/farm'
      fullPath: '/runs/farm'
      preLoaderRoute: typeof RunsFarmRouteImport
      parentRoute: typeof RunsRoute
    }
    '/charts/tier-trends': {
      id: '/charts/tier-trends'
      path: '/tier-trends'
      fullPath: '/charts/tier-trends'
      preLoaderRoute: typeof ChartsTierTrendsRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/charts/tier-stats': {
      id: '/charts/tier-stats'
      path: '/tier-stats'
      fullPath: '/charts/tier-stats'
      preLoaderRoute: typeof ChartsTierStatsRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/charts/sources': {
      id: '/charts/sources'
      path: '/sources'
      fullPath: '/charts/sources'
      preLoaderRoute: typeof ChartsSourcesRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/charts/fields': {
      id: '/charts/fields'
      path: '/fields'
      fullPath: '/charts/fields'
      preLoaderRoute: typeof ChartsFieldsRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/charts/deaths': {
      id: '/charts/deaths'
      path: '/deaths'
      fullPath: '/charts/deaths'
      preLoaderRoute: typeof ChartsDeathsRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/charts/coverage': {
      id: '/charts/coverage'
      path: '/coverage'
      fullPath: '/charts/coverage'
      preLoaderRoute: typeof ChartsCoverageRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/charts/coins': {
      id: '/charts/coins'
      path: '/coins'
      fullPath: '/charts/coins'
      preLoaderRoute: typeof ChartsCoinsRouteImport
      parentRoute: typeof ChartsRoute
    }
    '/charts/cells': {
      id: '/charts/cells'
      path: '/cells'
      fullPath: '/charts/cells'
      preLoaderRoute: typeof ChartsCellsRouteImport
      parentRoute: typeof ChartsRoute
    }
  }
}

interface ChartsRouteChildren {
  ChartsCellsRoute: typeof ChartsCellsRoute
  ChartsCoinsRoute: typeof ChartsCoinsRoute
  ChartsCoverageRoute: typeof ChartsCoverageRoute
  ChartsDeathsRoute: typeof ChartsDeathsRoute
  ChartsFieldsRoute: typeof ChartsFieldsRoute
  ChartsSourcesRoute: typeof ChartsSourcesRoute
  ChartsTierStatsRoute: typeof ChartsTierStatsRoute
  ChartsTierTrendsRoute: typeof ChartsTierTrendsRoute
  ChartsIndexRoute: typeof ChartsIndexRoute
}

const ChartsRouteChildren: ChartsRouteChildren = {
  ChartsCellsRoute: ChartsCellsRoute,
  ChartsCoinsRoute: ChartsCoinsRoute,
  ChartsCoverageRoute: ChartsCoverageRoute,
  ChartsDeathsRoute: ChartsDeathsRoute,
  ChartsFieldsRoute: ChartsFieldsRoute,
  ChartsSourcesRoute: ChartsSourcesRoute,
  ChartsTierStatsRoute: ChartsTierStatsRoute,
  ChartsTierTrendsRoute: ChartsTierTrendsRoute,
  ChartsIndexRoute: ChartsIndexRoute,
}

const ChartsRouteWithChildren =
  ChartsRoute._addFileChildren(ChartsRouteChildren)

interface RunsRouteChildren {
  RunsFarmRoute: typeof RunsFarmRoute
  RunsMilestoneRoute: typeof RunsMilestoneRoute
  RunsTournamentRoute: typeof RunsTournamentRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsFarmRoute: RunsFarmRoute,
  RunsMilestoneRoute: RunsMilestoneRoute,
  RunsTournamentRoute: RunsTournamentRoute,
  RunsIndexRoute: RunsIndexRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

interface SettingsRouteChildren {
  SettingsDeleteRoute: typeof SettingsDeleteRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsImportRoute: typeof SettingsImportRoute
  SettingsLocaleRoute: typeof SettingsLocaleRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsDeleteRoute: SettingsDeleteRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsLocaleRoute: SettingsLocaleRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsRoute: ChartsRouteWithChildren,
  RunsRoute: RunsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
